---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Create ArgoCD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: argocd
        state: present
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Install ArgoCD via official manifest
      command: >
        kubectl apply --validate=false -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply all ArgoCD apps
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', item) }}"
      with_fileglob:
        - "{{ playbook_dir }}/../../argocd/*-app.yaml"
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

