---
- name: Initialize Kubernetes control plane
  command: >
    kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init
  retries: 3
  delay: 30
  until: kubeadm_init is not failed
  ignore_errors: false

- name: Save kubeadm join command for workers
  shell: |
    kubeadm token create --print-join-command
  register: join_command
  changed_when: false
  retries: 3
  delay: 10

- name: Copy kubeconfig to regular user
  shell: |
    mkdir -p /home/{{ ansible_user | default('ubuntu') }}/.kube &&
    cp /etc/kubernetes/admin.conf /home/{{ ansible_user | default('ubuntu') }}/.kube/config &&
    chown {{ ansible_user | default('ubuntu') }}:{{ ansible_user | default('ubuntu') }} /home/{{ ansible_user | default('ubuntu') }}/.kube/config
  args:
    creates: "/home/{{ ansible_user | default('ubuntu') }}/.kube/config"
  retries: 2
  delay: 5

- name: Apply Flannel CNI
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  args:
    creates: /etc/cni/net.d/10-flannel.conflist
  retries: 3
  delay: 15
  register: flannel_apply
  until: flannel_apply is not failed

- name: Fetch admin.conf to local machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/admin.conf
    flat: yes
  retries: 3
  delay: 10

